trigger:
  - master

stages:
  - stage: Lint
    jobs:
      - job: Lint
        pool:
          vmImage: ubuntu-16.04
        variables:
          TARGET: x86_64-unknown-linux-gnu
        steps:
          - template: ci/azure-lint.yml

  - stage: Test
    jobs:
      - job: Linux
        pool:
          vmImage: ubuntu-16.04
        steps:
          - template: ci/azure-steps.yml
        strategy:
          matrix:
            x86_64:
              TARGET: x86_64-unknown-linux-gnu
            i686:
              TARGET: i686-unknown-linux-gnu
            x86_64-beta:
              TARGET: x86_64-unknown-linux-gnu
              TOOLCHAIN: beta
            x86_64-nightly:
              TARGET: x86_64-unknown-linux-gnu
              TOOLCHAIN: nightly

      - job: macOS
        pool:
          vmImage: macos-10.13
        steps:
          - template: ci/azure-steps.yml
        strategy:
          matrix:
            x86_64:
              TARGET: x86_64-apple-darwin

      - job: Windows_vs2019
        pool:
          vmImage: windows-2019
        steps:
          - template: ci/azure-steps.yml
        strategy:
          matrix:
            x86_64-msvc:
              TARGET: x86_64-pc-windows-msvc

      - job: Windows_vs2017
        pool:
          vmImage: vs2017-win2016
        steps:
          - template: ci/azure-steps.yml
        strategy:
          matrix:
            x86_64-msvc:
              TARGET: x86_64-pc-windows-msvc
            i686-msvc:
              TARGET: i686-pc-windows-msvc
            x86_64-gnu:
              TARGET: x86_64-pc-windows-gnu
            i686-gnu:
              TARGET: i686-pc-windows-gnu

      - job: Windows_vs2015
        pool:
          vmImage: vs2015-win2012r2
        steps:
          - template: ci/azure-steps.yml
        strategy:
          matrix:
            x86_64-msvc:
              TARGET: x86_64-pc-windows-msvc
            i686-msvc:
              TARGET: i686-pc-windows-msvc

  - stage: Coverage
    jobs:
      - job: Coverage
        pool:
          vmImage: ubuntu-16.04
        variables:
          TARGET: x86_64-unknown-linux-gnu
          TOOLCHAIN: nightly
        steps:
          - template: ci/azure-coverage.yml
