# requirements are relaxed due to inaccuracies of rust coverage tooling and
# unexpected coverage changes

coverage:
  status:
    project:
      default:
        target: 95
        threshold: 1.5
    patch:
      default:
        target: 95
        threshold: null
